### ISSUE TITLE
Можно ли добавить краткую информацию о работе алгоритма? 

### ISSUE THREAD

**Issue by kiriharu** [undefinedvalue0103/okdacrypt#1]
Можно ли добавить краткую информацию о работе алгоритма? О его функциях, о том что используется или просто добавить в код комментарии?

**Comment by hatkidchan** [comment]
Добавил описание работы алгоритма в README.md. Надеюсь, оказалось полезным.

Если есть идеи по улучшению алгоритма - буду рад принять их
